name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'ğŸš€ Features'
    label: 'Feature'
  - title: 'âš ï¸ Fixes'
    label: 'Bug'
  - title: 'ğŸ“ƒ ETC'
    label:
      - 'Refactor'
      - 'Docs'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
version-resolver:
  major:
    labels:
      - 'âœ¨ major'
  minor:
    labels:
      - 'âœ¨ minor'
  patch:
    labels:
      - 'âœ¨ patch'
  default: patch
template: |
  ## ğŸ’¡ Updates
  ---
  $CHANGES
no-changes-template: 'No Updates'


